[book]
title = "食单集注"
language = "zh-Hans"

[output.html]
default-theme = "dark" 
preferred-dark-theme = "ayu"
fold = {enable = true, level = 1}
additional-css = ["book.css"]

[output.html.search]
enable = false

[output.infisearch]
enable = true
lang = "chinese"

