[book]
title = "食单集注"
language = "zh-Hans"

[output.html]
default-theme = "dark" 
preferred-dark-theme = "ayu"
fold = {enable = true, level = 1}
additional-css = ["book.css"]
search = false

[output.infisearch]
# 啟用中文分詞支持
lang = "chinese" 

