[book]
title = "食单集注"
language = "zh"

[output.html]
default-theme = "dark" 
preferred-dark-theme = "ayu"
fold = {enable = true, level = 1}
additional-css = ["src/assets/book.css"]
additional-js = ["src/assets/fzf.umd.js", "src/assets/elasticlunr.js"]

[output.html.search]
enable = true
limit-results = 1000

